# -----------------------------------------------------------------------------
# CONFIDENTIAL AND PROPRIETARY. COPYRIGHT (C) 2011 ALI Solutions Inc.
# This software code contains proprietary trade secrets of ALI Solutions Inc.
# and is also protected by U.S. and other copyright laws and applicable
# international treaties. Any use, compilation, modification, distribution,
# reproduction, performance, display, or disclosure ("Use") of this software
# code is subject to the terms and conditions of your written agreement with
# ALI Solutions Inc. If you do not have such an agreement, then any Use of this
# material is strictly prohibited. Unauthorized Use of this software code,
# or any portion of it, will result in civil liability and/or criminal penalties.
# By modifying this software code, you agree to assign any and all intellectual
# property rights related in any way to your modification to ALI Solutions Inc.
# pursuant to your written agreement with ALI Solutions Inc.
# -----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
#
# SUBROUTINE: set_dirs_template.PL
#
# PARAMETERS: none
#
# DESCRIPTION: Customer specific configuration is done here.
#
#-----------------------------------------------------------------------------

sub set_dirs {

    require ("util.PL");
    require ("custom_score.PL");

    

} # end of sub set_dirs.PL

1;
